### PR TITLE
fix: validate project named passed as CLI option, allow and escape kebab-case project name

### LINKED ISSUE #317: Transform package names for iOS/Android
## Environment

RNEF 0.7.6
Create test app straight from template and make it contains hyphen (-), e.g. `brownfield-test`

## Description

When app name contains hyphen, then the iOS package names becomes invalid:
```
warn Invalid application's package name "com.brownfield-test" in either 'AndroidManifest.xml' or 'build.gradle'. Read guidelines for setting the package name here: https://developer.android.com/studio/build/application-id
```

This could be easily avoided if we either:
1. Disallowed hyphens (but I like hypens, they are so popular in JS)
2. If the name contains hyphens, transform it from kebab-case to PascalCase for iOS/Android use cases.

### PR DESCRIPTION
**Pull request by mdjastrzebski**
### Summary

Resolves #317

Scope:
- validate project name passed as CLI option (positional arg or `-d` option)
- allow for kebab-case names, by transforming them into PascalCase

CleanShot 2025-05-12 at 17 36 06@2x

### Test plan

Manually test `@rnef/create-app` for kabab-case or invalid project names.

### CODE REVIEW

File: packages/create-app/src/lib/bin.ts [hunk 1]
```diff
@@ -65,8 +69,12 @@ export async function run() {
 
   printWelcomeMessage();
 
-  const projectName =
+  let projectName =
     (options.dir || options.name) ?? (await promptProjectName());
+  if (validateProjectName(projectName)) {
+    projectName = await promptProjectName(projectName);
```
Comment (thymikee) [inline packages/create-app/src/lib/bin.ts:75]: `validateProjectName` may return a string with error message. I think it would be weird if it ended up as a suggestion for a name in this prompt?

**Review by thymikee — APPROVED** [review]
